2022-11-22 19:14:58,602 INFO    StreamThr :37387 [internal.py:wandb_internal():88] W&B internal server running at pid: 37387, started at: 2022-11-22 19:14:58.601050
2022-11-22 19:14:58,604 DEBUG   HandlerThread:37387 [handler.py:handle_request():139] handle_request: status
2022-11-22 19:14:58,606 DEBUG   SenderThread:37387 [sender.py:send_request():317] send_request: status
2022-11-22 19:14:58,608 DEBUG   SenderThread:37387 [sender.py:send():303] send: header
2022-11-22 19:14:58,608 DEBUG   SenderThread:37387 [sender.py:send():303] send: run
2022-11-22 19:14:58,608 INFO    WriterThread:37387 [datastore.py:open_for_write():75] open: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191458-2vt5gtb1/run-2vt5gtb1.wandb
2022-11-22 19:14:58,629 INFO    SenderThread:37387 [sender.py:_maybe_setup_resume():593] checking resume status for None/YOLOR/2vt5gtb1
2022-11-22 19:15:00,297 DEBUG   HandlerThread:37387 [handler.py:handle_request():139] handle_request: check_version
2022-11-22 19:15:00,299 INFO    SenderThread:37387 [dir_watcher.py:__init__():216] watching files in: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191458-2vt5gtb1/files
2022-11-22 19:15:00,299 INFO    SenderThread:37387 [sender.py:_start_run_threads():928] run started: 2vt5gtb1 with start time 1669115698.594434
2022-11-22 19:15:00,300 DEBUG   SenderThread:37387 [sender.py:send():303] send: summary
2022-11-22 19:15:00,300 INFO    SenderThread:37387 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2022-11-22 19:15:00,300 DEBUG   SenderThread:37387 [sender.py:send_request():317] send_request: check_version
2022-11-22 19:15:01,308 INFO    Thread-17 :37387 [dir_watcher.py:_on_file_created():275] file/dir created: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191458-2vt5gtb1/files/wandb-summary.json
2022-11-22 19:15:02,071 DEBUG   HandlerThread:37387 [handler.py:handle_request():139] handle_request: run_start
2022-11-22 19:15:02,073 DEBUG   HandlerThread:37387 [system_info.py:__init__():31] System info init
2022-11-22 19:15:02,073 DEBUG   HandlerThread:37387 [system_info.py:__init__():46] System info init done
2022-11-22 19:15:02,073 INFO    HandlerThread:37387 [system_monitor.py:start():150] Starting system monitor
2022-11-22 19:15:02,074 INFO    SystemMonitor:37387 [system_monitor.py:_start():116] Starting system asset monitoring threads
2022-11-22 19:15:02,074 INFO    SystemMonitor:37387 [interfaces.py:start():168] Started cpu
2022-11-22 19:15:02,075 INFO    SystemMonitor:37387 [interfaces.py:start():168] Started disk
2022-11-22 19:15:02,075 INFO    SystemMonitor:37387 [interfaces.py:start():168] Started gpu
2022-11-22 19:15:02,076 INFO    SystemMonitor:37387 [interfaces.py:start():168] Started memory
2022-11-22 19:15:02,076 INFO    HandlerThread:37387 [system_monitor.py:probe():168] Collecting system info
2022-11-22 19:15:02,076 INFO    SystemMonitor:37387 [interfaces.py:start():168] Started network
2022-11-22 19:15:02,103 DEBUG   HandlerThread:37387 [system_info.py:probe():195] Probing system
2022-11-22 19:15:02,107 DEBUG   HandlerThread:37387 [git.py:repo():40] git repository is invalid
2022-11-22 19:15:02,108 DEBUG   HandlerThread:37387 [system_info.py:probe():241] Probing system done
2022-11-22 19:15:02,108 DEBUG   HandlerThread:37387 [system_monitor.py:probe():177] {'os': 'Linux-5.15.0-53-generic-x86_64-with-glibc2.17', 'python': '3.8.13', 'heartbeatAt': '2022-11-22T11:15:02.103790', 'startedAt': '2022-11-22T11:14:58.567254', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/home/rp/DeepLearning/yolov7-main/train.py', 'codePath': 'train.py', 'host': 'rp', 'username': 'rp', 'executable': '/home/rp/Softwares/anaconda3/envs/dyh/bin/python', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 2979.1704375, 'min': 800.0, 'max': 4800.0}, 'cpu_freq_per_core': [{'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 4166.727, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}, {'current': 2900.0, 'min': 800.0, 'max': 4800.0}], 'disk': {'total': 937.3305015563965, 'used': 300.8201217651367}, 'gpu': 'NVIDIA GeForce RTX 3080', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3080', 'memory_total': 10497294336}], 'memory': {'total': 31.272598266601562}}
2022-11-22 19:15:02,108 INFO    HandlerThread:37387 [system_monitor.py:probe():178] Finished collecting system info
2022-11-22 19:15:02,108 INFO    HandlerThread:37387 [system_monitor.py:probe():181] Publishing system info
2022-11-22 19:15:02,108 DEBUG   HandlerThread:37387 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2022-11-22 19:15:02,110 DEBUG   HandlerThread:37387 [system_info.py:_save_pip():67] Saving pip packages done
2022-11-22 19:15:02,110 DEBUG   HandlerThread:37387 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2022-11-22 19:15:02,306 INFO    Thread-17 :37387 [dir_watcher.py:_on_file_created():275] file/dir created: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191458-2vt5gtb1/files/conda-environment.yaml
2022-11-22 19:15:02,307 INFO    Thread-17 :37387 [dir_watcher.py:_on_file_created():275] file/dir created: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191458-2vt5gtb1/files/requirements.txt
2022-11-22 19:15:04,476 DEBUG   HandlerThread:37387 [system_info.py:_save_conda():86] Saving conda packages done
2022-11-22 19:15:04,483 INFO    HandlerThread:37387 [system_monitor.py:probe():183] Finished publishing system info
2022-11-22 19:15:04,520 DEBUG   SenderThread:37387 [sender.py:send():303] send: files
2022-11-22 19:15:04,520 INFO    SenderThread:37387 [sender.py:_save_file():1171] saving file wandb-metadata.json with policy now
2022-11-22 19:15:04,530 DEBUG   HandlerThread:37387 [handler.py:handle_request():139] handle_request: stop_status
2022-11-22 19:15:04,531 DEBUG   SenderThread:37387 [sender.py:send_request():317] send_request: stop_status
2022-11-22 19:15:05,303 INFO    Thread-17 :37387 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191458-2vt5gtb1/files/conda-environment.yaml
2022-11-22 19:15:05,303 INFO    Thread-17 :37387 [dir_watcher.py:_on_file_created():275] file/dir created: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191458-2vt5gtb1/files/wandb-metadata.json
2022-11-22 19:15:06,504 DEBUG   HandlerThread:37387 [handler.py:handle_request():139] handle_request: poll_exit
2022-11-22 19:15:11,506 DEBUG   HandlerThread:37387 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:15:16,509 DEBUG   HandlerThread:37387 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:15:20,045 DEBUG   SenderThread:37387 [sender.py:send():303] send: telemetry
2022-11-22 19:15:20,046 DEBUG   SenderThread:37387 [sender.py:send():303] send: telemetry
2022-11-22 19:15:20,046 DEBUG   SenderThread:37387 [sender.py:send():303] send: config
2022-11-22 19:15:20,046 DEBUG   SenderThread:37387 [sender.py:send():303] send: config
2022-11-22 19:15:20,057 DEBUG   SenderThread:37387 [sender.py:send():303] send: exit
2022-11-22 19:15:20,057 INFO    SenderThread:37387 [sender.py:send_exit():442] handling exit code: 0
2022-11-22 19:15:20,058 INFO    SenderThread:37387 [sender.py:send_exit():444] handling runtime: 3
2022-11-22 19:15:20,064 INFO    SenderThread:37387 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2022-11-22 19:15:20,065 INFO    SenderThread:37387 [sender.py:send_exit():450] send defer
2022-11-22 19:15:20,065 DEBUG   SenderThread:37387 [sender.py:send_request():317] send_request: poll_exit
2022-11-22 19:15:20,065 DEBUG   HandlerThread:37387 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:15:20,065 INFO    HandlerThread:37387 [handler.py:handle_request_defer():162] handle defer: 0
2022-11-22 19:15:20,066 DEBUG   SenderThread:37387 [sender.py:send_request():317] send_request: defer
2022-11-22 19:15:20,066 INFO    SenderThread:37387 [sender.py:send_request_defer():459] handle sender defer: 0
2022-11-22 19:15:20,066 INFO    SenderThread:37387 [sender.py:transition_state():463] send defer: 1
2022-11-22 19:15:20,067 DEBUG   HandlerThread:37387 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:15:20,067 INFO    HandlerThread:37387 [handler.py:handle_request_defer():162] handle defer: 1
2022-11-22 19:15:20,067 INFO    HandlerThread:37387 [system_monitor.py:finish():160] Stopping system monitor
2022-11-22 19:15:20,067 DEBUG   SystemMonitor:37387 [system_monitor.py:_start():130] Starting system metrics aggregation loop
2022-11-22 19:15:20,068 DEBUG   SystemMonitor:37387 [system_monitor.py:_start():137] Finished system metrics aggregation loop
2022-11-22 19:15:20,068 DEBUG   SystemMonitor:37387 [system_monitor.py:_start():141] Publishing last batch of metrics
2022-11-22 19:15:20,069 INFO    HandlerThread:37387 [interfaces.py:finish():173] Joined cpu
2022-11-22 19:15:20,069 INFO    HandlerThread:37387 [interfaces.py:finish():173] Joined disk
2022-11-22 19:15:20,113 INFO    HandlerThread:37387 [interfaces.py:finish():173] Joined gpu
2022-11-22 19:15:20,113 INFO    HandlerThread:37387 [interfaces.py:finish():173] Joined memory
2022-11-22 19:15:20,113 INFO    HandlerThread:37387 [interfaces.py:finish():173] Joined network
2022-11-22 19:15:20,114 DEBUG   SenderThread:37387 [sender.py:send_request():317] send_request: defer
2022-11-22 19:15:20,114 INFO    SenderThread:37387 [sender.py:send_request_defer():459] handle sender defer: 1
2022-11-22 19:15:20,114 INFO    SenderThread:37387 [sender.py:transition_state():463] send defer: 2
2022-11-22 19:15:20,114 DEBUG   SenderThread:37387 [sender.py:send():303] send: stats
2022-11-22 19:15:20,114 DEBUG   HandlerThread:37387 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:15:20,114 INFO    HandlerThread:37387 [handler.py:handle_request_defer():162] handle defer: 2
2022-11-22 19:15:20,114 DEBUG   SenderThread:37387 [sender.py:send_request():317] send_request: defer
2022-11-22 19:15:20,115 INFO    SenderThread:37387 [sender.py:send_request_defer():459] handle sender defer: 2
2022-11-22 19:15:20,115 INFO    SenderThread:37387 [sender.py:transition_state():463] send defer: 3
2022-11-22 19:15:20,115 DEBUG   HandlerThread:37387 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:15:20,115 INFO    HandlerThread:37387 [handler.py:handle_request_defer():162] handle defer: 3
2022-11-22 19:15:20,115 DEBUG   SenderThread:37387 [sender.py:send_request():317] send_request: defer
2022-11-22 19:15:20,115 INFO    SenderThread:37387 [sender.py:send_request_defer():459] handle sender defer: 3
2022-11-22 19:15:20,115 INFO    SenderThread:37387 [sender.py:transition_state():463] send defer: 4
2022-11-22 19:15:20,115 DEBUG   HandlerThread:37387 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:15:20,116 INFO    HandlerThread:37387 [handler.py:handle_request_defer():162] handle defer: 4
2022-11-22 19:15:20,116 DEBUG   SenderThread:37387 [sender.py:send():303] send: summary
2022-11-22 19:15:20,116 INFO    SenderThread:37387 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2022-11-22 19:15:20,116 DEBUG   SenderThread:37387 [sender.py:send_request():317] send_request: defer
2022-11-22 19:15:20,116 INFO    SenderThread:37387 [sender.py:send_request_defer():459] handle sender defer: 4
2022-11-22 19:15:20,116 INFO    SenderThread:37387 [sender.py:transition_state():463] send defer: 5
2022-11-22 19:15:20,117 DEBUG   HandlerThread:37387 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:15:20,117 INFO    HandlerThread:37387 [handler.py:handle_request_defer():162] handle defer: 5
2022-11-22 19:15:20,117 DEBUG   SenderThread:37387 [sender.py:send_request():317] send_request: defer
2022-11-22 19:15:20,117 INFO    SenderThread:37387 [sender.py:send_request_defer():459] handle sender defer: 5
2022-11-22 19:15:20,320 INFO    Thread-17 :37387 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191458-2vt5gtb1/files/wandb-summary.json
2022-11-22 19:15:20,321 INFO    Thread-17 :37387 [dir_watcher.py:_on_file_created():275] file/dir created: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191458-2vt5gtb1/files/output.log
2022-11-22 19:15:21,513 DEBUG   HandlerThread:37387 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:15:22,323 INFO    Thread-17 :37387 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191458-2vt5gtb1/files/output.log
2022-11-22 19:15:25,669 INFO    SenderThread:37387 [sender.py:transition_state():463] send defer: 6
2022-11-22 19:15:25,670 DEBUG   HandlerThread:37387 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:15:25,670 INFO    HandlerThread:37387 [handler.py:handle_request_defer():162] handle defer: 6
2022-11-22 19:15:25,670 DEBUG   SenderThread:37387 [sender.py:send_request():317] send_request: defer
2022-11-22 19:15:25,670 INFO    SenderThread:37387 [sender.py:send_request_defer():459] handle sender defer: 6
2022-11-22 19:15:26,142 INFO    SenderThread:37387 [sender.py:transition_state():463] send defer: 7
2022-11-22 19:15:26,144 DEBUG   HandlerThread:37387 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:15:26,144 INFO    HandlerThread:37387 [handler.py:handle_request_defer():162] handle defer: 7
2022-11-22 19:15:26,145 DEBUG   SenderThread:37387 [sender.py:send_request():317] send_request: defer
2022-11-22 19:15:26,146 INFO    SenderThread:37387 [sender.py:send_request_defer():459] handle sender defer: 7
2022-11-22 19:15:26,146 INFO    SenderThread:37387 [dir_watcher.py:finish():362] shutting down directory watcher
2022-11-22 19:15:26,326 INFO    SenderThread:37387 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191458-2vt5gtb1/files/output.log
2022-11-22 19:15:26,326 INFO    SenderThread:37387 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191458-2vt5gtb1/files/config.yaml
2022-11-22 19:15:26,328 INFO    SenderThread:37387 [dir_watcher.py:finish():392] scan: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191458-2vt5gtb1/files
2022-11-22 19:15:26,328 INFO    SenderThread:37387 [dir_watcher.py:finish():406] scan save: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191458-2vt5gtb1/files/wandb-summary.json wandb-summary.json
2022-11-22 19:15:26,329 INFO    SenderThread:37387 [dir_watcher.py:finish():406] scan save: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191458-2vt5gtb1/files/config.yaml config.yaml
2022-11-22 19:15:26,335 INFO    SenderThread:37387 [dir_watcher.py:finish():406] scan save: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191458-2vt5gtb1/files/output.log output.log
2022-11-22 19:15:26,336 INFO    SenderThread:37387 [dir_watcher.py:finish():406] scan save: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191458-2vt5gtb1/files/requirements.txt requirements.txt
2022-11-22 19:15:26,336 INFO    SenderThread:37387 [dir_watcher.py:finish():406] scan save: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191458-2vt5gtb1/files/conda-environment.yaml conda-environment.yaml
2022-11-22 19:15:26,337 INFO    SenderThread:37387 [dir_watcher.py:finish():406] scan save: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191458-2vt5gtb1/files/wandb-metadata.json wandb-metadata.json
2022-11-22 19:15:26,337 INFO    SenderThread:37387 [sender.py:transition_state():463] send defer: 8
2022-11-22 19:15:26,355 DEBUG   HandlerThread:37387 [handler.py:handle_request():139] handle_request: defer
2022-11-22 19:15:26,356 INFO    HandlerThread:37387 [handler.py:handle_request_defer():162] handle defer: 8
2022-11-22 19:15:26,372 DEBUG   SenderThread:37387 [sender.py:send_request():317] send_request: defer
2022-11-22 19:15:26,372 INFO    SenderThread:37387 [sender.py:send_request_defer():459] handle sender defer: 8
2022-11-22 19:15:26,372 INFO    SenderThread:37387 [file_pusher.py:finish():168] shutting down file pusher
2022-11-22 19:15:26,516 DEBUG   HandlerThread:37387 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:15:30,070 ERROR   Thread-20 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/wandb-metadata.json?Expires=1669202119&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vb0CRMCq988DTCyaZJIquQPI65NLK5RNT8aexZJrsg3rAYec7r31HrVzSIsmT5YF4Zv6DlaYIETAGXp4%2B1%2FtnLiwDoq9iYlK%2FOdMGcXJ%2BcLOEEWpsFvZSyaA%2FzVH9DBpB5urleq0oHiJ%2BsnNBZhuN0U9f2dlwrUJi4M7D7pNdMm2DOOFnTHayb2JWbDcfaiwTODwUwT4neM58ey7tue2toTNXuhtJuJmJjeXcxEfc7xxKUydvxRKqvHg%2BaGaYuYZ6tQ3VkdpBo52f3ngzRxsK7WCeFDx%2BwYeWTq%2BW%2BpvRLN9zxi15Y9fPUUzVAvgb9uaIZK9efrVSDRlzGSoeESXdg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/wandb-metadata.json?Expires=1669202119&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vb0CRMCq988DTCyaZJIquQPI65NLK5RNT8aexZJrsg3rAYec7r31HrVzSIsmT5YF4Zv6DlaYIETAGXp4%2B1%2FtnLiwDoq9iYlK%2FOdMGcXJ%2BcLOEEWpsFvZSyaA%2FzVH9DBpB5urleq0oHiJ%2BsnNBZhuN0U9f2dlwrUJi4M7D7pNdMm2DOOFnTHayb2JWbDcfaiwTODwUwT4neM58ey7tue2toTNXuhtJuJmJjeXcxEfc7xxKUydvxRKqvHg%2BaGaYuYZ6tQ3VkdpBo52f3ngzRxsK7WCeFDx%2BwYeWTq%2BW%2BpvRLN9zxi15Y9fPUUzVAvgb9uaIZK9efrVSDRlzGSoeESXdg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c84b5430>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:15:30,070 ERROR   Thread-20 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2652'}
2022-11-22 19:15:30,070 ERROR   Thread-20 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:15:31,522 DEBUG   HandlerThread:37387 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:15:36,524 DEBUG   HandlerThread:37387 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:15:41,347 ERROR   Thread-20 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/wandb-metadata.json?Expires=1669202119&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vb0CRMCq988DTCyaZJIquQPI65NLK5RNT8aexZJrsg3rAYec7r31HrVzSIsmT5YF4Zv6DlaYIETAGXp4%2B1%2FtnLiwDoq9iYlK%2FOdMGcXJ%2BcLOEEWpsFvZSyaA%2FzVH9DBpB5urleq0oHiJ%2BsnNBZhuN0U9f2dlwrUJi4M7D7pNdMm2DOOFnTHayb2JWbDcfaiwTODwUwT4neM58ey7tue2toTNXuhtJuJmJjeXcxEfc7xxKUydvxRKqvHg%2BaGaYuYZ6tQ3VkdpBo52f3ngzRxsK7WCeFDx%2BwYeWTq%2BW%2BpvRLN9zxi15Y9fPUUzVAvgb9uaIZK9efrVSDRlzGSoeESXdg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/wandb-metadata.json?Expires=1669202119&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vb0CRMCq988DTCyaZJIquQPI65NLK5RNT8aexZJrsg3rAYec7r31HrVzSIsmT5YF4Zv6DlaYIETAGXp4%2B1%2FtnLiwDoq9iYlK%2FOdMGcXJ%2BcLOEEWpsFvZSyaA%2FzVH9DBpB5urleq0oHiJ%2BsnNBZhuN0U9f2dlwrUJi4M7D7pNdMm2DOOFnTHayb2JWbDcfaiwTODwUwT4neM58ey7tue2toTNXuhtJuJmJjeXcxEfc7xxKUydvxRKqvHg%2BaGaYuYZ6tQ3VkdpBo52f3ngzRxsK7WCeFDx%2BwYeWTq%2BW%2BpvRLN9zxi15Y9fPUUzVAvgb9uaIZK9efrVSDRlzGSoeESXdg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c84ab8b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:15:41,348 ERROR   Thread-20 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2652'}
2022-11-22 19:15:41,348 ERROR   Thread-20 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:15:41,527 DEBUG   HandlerThread:37387 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:15:46,530 DEBUG   HandlerThread:37387 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:15:51,532 DEBUG   HandlerThread:37387 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:15:51,930 ERROR   Thread-25 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/conda-environment.yaml?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=OaUG6QXNz%2FTlE6iOzLGAD%2Bhg9CfkQtXLH5nTRLTw9guiGtxCtw%2FvHdjZ0TD%2BYiDgJD4a02dvFuxSt0%2B7AhXP%2Fei8a%2BAo%2B7aqstpjNlApPtnDFc9tfaRFfwm6m0fv%2BkLHsawUCnKv6%2Bkg6%2FjKaxNnkKlo5cIY22Q%2FUVtDtI6L3xaW1ILbxXp2L0Boa49cq5vH5XF2j266%2BMHwSwVeCRZo3f3lmTrRbWPeZVgsTm0hJgNAbjziNTFz3eSdIIvfA4C2tM8SkYsEjimECGaBOqU5TgOWWJlwTi2Jy6oO3jL9%2FcXpM8RLNcqAM2Cgzo2qFJytSyHMFoue3RBv6aY4s8Yj3w%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/conda-environment.yaml?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=OaUG6QXNz%2FTlE6iOzLGAD%2Bhg9CfkQtXLH5nTRLTw9guiGtxCtw%2FvHdjZ0TD%2BYiDgJD4a02dvFuxSt0%2B7AhXP%2Fei8a%2BAo%2B7aqstpjNlApPtnDFc9tfaRFfwm6m0fv%2BkLHsawUCnKv6%2Bkg6%2FjKaxNnkKlo5cIY22Q%2FUVtDtI6L3xaW1ILbxXp2L0Boa49cq5vH5XF2j266%2BMHwSwVeCRZo3f3lmTrRbWPeZVgsTm0hJgNAbjziNTFz3eSdIIvfA4C2tM8SkYsEjimECGaBOqU5TgOWWJlwTi2Jy6oO3jL9%2FcXpM8RLNcqAM2Cgzo2qFJytSyHMFoue3RBv6aY4s8Yj3w%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c847ff10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:15:51,930 ERROR   Thread-25 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6342'}
2022-11-22 19:15:51,930 ERROR   Thread-25 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:15:51,938 ERROR   Thread-23 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/output.log?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Da9t7UJRzL8KOppQ0LGm8uCvE56atWOTDjF9NjCEr5d4jhQMjkK2S4wUeV2rjileH%2BEJFdjMpn3PYcIPoMNP0XtIoTFnzYlC%2F908fGpc3Lt0IAtYvV4Ol5s5SI7DA7OBpP3GDQ4z%2BQRhGkIkiu6Ku%2F5mWejTG0p3vPSMny2rq%2F0gjdmKCQYHJ%2FApGpxJbjTeuKaFpXsVPKym9%2Ftd4gTXA%2BZKmvHC%2FCLsxwt32aOfjGxRdsr%2FpB6OIJ3IdPnS31an6hgsPy5JKVcVHnug24EG09EXVd8WrgHv6OLn8Ng%2BZzr480%2Bb5IaS2RytC%2BYTDn3XWBw2qmig7IxK6u3rnu6YoQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/output.log?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Da9t7UJRzL8KOppQ0LGm8uCvE56atWOTDjF9NjCEr5d4jhQMjkK2S4wUeV2rjileH%2BEJFdjMpn3PYcIPoMNP0XtIoTFnzYlC%2F908fGpc3Lt0IAtYvV4Ol5s5SI7DA7OBpP3GDQ4z%2BQRhGkIkiu6Ku%2F5mWejTG0p3vPSMny2rq%2F0gjdmKCQYHJ%2FApGpxJbjTeuKaFpXsVPKym9%2Ftd4gTXA%2BZKmvHC%2FCLsxwt32aOfjGxRdsr%2FpB6OIJ3IdPnS31an6hgsPy5JKVcVHnug24EG09EXVd8WrgHv6OLn8Ng%2BZzr480%2Bb5IaS2RytC%2BYTDn3XWBw2qmig7IxK6u3rnu6YoQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c847fd60>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:15:51,938 ERROR   Thread-23 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '11198'}
2022-11-22 19:15:51,938 ERROR   Thread-23 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:15:51,942 ERROR   Thread-24 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/requirements.txt?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=AO6%2F5byvkZpfRQDchG8Vy6O2iAyDFFiWnDanTGNvzZx%2FWbVNe4jj80rn16hAvXVV%2FMUbpeYAzDB6Cx5CDMr5Z3vTgINGb9UzDJnD5NZnF8AkOFtd%2BjONVaXIeV94%2BUToJYLJa2sJ8%2FOAW2sF3Ccbj5rybvUh95RiOEMxpKmomjblsr6B7AoFDPtRUeyKdrg%2F3h5dRIws4kOuJ7Xx6GWN51n1zxQipxuX%2FFFf%2BXHyyllX7wqpCLmLRXwp3KTe8J%2F1Y8ttMoyZ8034WaYA9bC%2B0eRHdrgQsRJNdKRA38g86mzYo1fV0AZvdWpGxpVCm96S6KsOZ2yaP88XkEXo6uwWLg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/requirements.txt?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=AO6%2F5byvkZpfRQDchG8Vy6O2iAyDFFiWnDanTGNvzZx%2FWbVNe4jj80rn16hAvXVV%2FMUbpeYAzDB6Cx5CDMr5Z3vTgINGb9UzDJnD5NZnF8AkOFtd%2BjONVaXIeV94%2BUToJYLJa2sJ8%2FOAW2sF3Ccbj5rybvUh95RiOEMxpKmomjblsr6B7AoFDPtRUeyKdrg%2F3h5dRIws4kOuJ7Xx6GWN51n1zxQipxuX%2FFFf%2BXHyyllX7wqpCLmLRXwp3KTe8J%2F1Y8ttMoyZ8034WaYA9bC%2B0eRHdrgQsRJNdKRA38g86mzYo1fV0AZvdWpGxpVCm96S6KsOZ2yaP88XkEXo6uwWLg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c847fdc0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:15:51,942 ERROR   Thread-24 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2140'}
2022-11-22 19:15:51,942 ERROR   Thread-24 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:15:51,959 ERROR   Thread-22 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/config.yaml?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=QuoiPlWEUg%2FwmuqrLgbKBgCQhd2Tt1lNE1O1%2BwuI1mjVEKmzltZ57Z%2BmesWBfz4HWYCuqlG0cWPVStkQl8H9cpY3J1NZPYiIlTo3Wd7ZEwECQTTQDYe9SgFXfvSoZPvX%2FJ8zz0G7GXDtqGEgznk8gP8GvzKTllg34E0zdRwgVC5OZeG73edS2%2F7%2FxmtUK9osx6ydbwo8X1%2FfqA%2F1i0Thv9MobwhvUCE3hJCQgK00Hbj4pyAhvYmgfhr2oayEZ9eBK20vNMHpMNXPbKOTKCd07L%2BL7upteHiArR65W753ZXw8YJOr%2BhQdLpt7vYIX9kcNF7dfS%2Bma7cAdATKSgrcVGw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/config.yaml?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=QuoiPlWEUg%2FwmuqrLgbKBgCQhd2Tt1lNE1O1%2BwuI1mjVEKmzltZ57Z%2BmesWBfz4HWYCuqlG0cWPVStkQl8H9cpY3J1NZPYiIlTo3Wd7ZEwECQTTQDYe9SgFXfvSoZPvX%2FJ8zz0G7GXDtqGEgznk8gP8GvzKTllg34E0zdRwgVC5OZeG73edS2%2F7%2FxmtUK9osx6ydbwo8X1%2FfqA%2F1i0Thv9MobwhvUCE3hJCQgK00Hbj4pyAhvYmgfhr2oayEZ9eBK20vNMHpMNXPbKOTKCd07L%2BL7upteHiArR65W753ZXw8YJOr%2BhQdLpt7vYIX9kcNF7dfS%2Bma7cAdATKSgrcVGw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c85053d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:15:51,959 ERROR   Thread-22 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5112'}
2022-11-22 19:15:51,959 ERROR   Thread-22 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:15:52,215 ERROR   Thread-21 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/wandb-summary.json?Expires=1669202142&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=SuTOwp%2FBVfFV%2B5mYZ4Ve%2BxcIJJylnXDIdS8cixsfr0QT1cSU34JJwmGTRrqy5v33IlutI40GAsDt46iaOiTxU78EmAIe%2F5LQtiP7%2BMFigx%2FITG3f9y5rn1sXvzKI9u5aHcJSYYLaUP8gPg2ddeknWfqVjC0nMdkEDd2p%2B0HP7eNvYybf7oxKe%2FH15tehfeFyPdtPlEqqug4gRESBPg2uCbLZwYUZeejJCBgT%2BNpdO4z8fUjvkW%2B%2B04tWOS0Kjp4M4X%2BGRTWB4krKr%2F2z5ckVKbUQXGMXeRg2s1tJ%2BZTclptKIYmFYFveOI3VSlbgB0o11s6YEc5anf7MpjjJB4xcKw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/wandb-summary.json?Expires=1669202142&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=SuTOwp%2FBVfFV%2B5mYZ4Ve%2BxcIJJylnXDIdS8cixsfr0QT1cSU34JJwmGTRrqy5v33IlutI40GAsDt46iaOiTxU78EmAIe%2F5LQtiP7%2BMFigx%2FITG3f9y5rn1sXvzKI9u5aHcJSYYLaUP8gPg2ddeknWfqVjC0nMdkEDd2p%2B0HP7eNvYybf7oxKe%2FH15tehfeFyPdtPlEqqug4gRESBPg2uCbLZwYUZeejJCBgT%2BNpdO4z8fUjvkW%2B%2B04tWOS0Kjp4M4X%2BGRTWB4krKr%2F2z5ckVKbUQXGMXeRg2s1tJ%2BZTclptKIYmFYFveOI3VSlbgB0o11s6YEc5anf7MpjjJB4xcKw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c8450430>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:15:52,217 ERROR   Thread-21 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2022-11-22 19:15:52,217 ERROR   Thread-21 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:15:53,786 ERROR   Thread-20 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/wandb-metadata.json?Expires=1669202119&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vb0CRMCq988DTCyaZJIquQPI65NLK5RNT8aexZJrsg3rAYec7r31HrVzSIsmT5YF4Zv6DlaYIETAGXp4%2B1%2FtnLiwDoq9iYlK%2FOdMGcXJ%2BcLOEEWpsFvZSyaA%2FzVH9DBpB5urleq0oHiJ%2BsnNBZhuN0U9f2dlwrUJi4M7D7pNdMm2DOOFnTHayb2JWbDcfaiwTODwUwT4neM58ey7tue2toTNXuhtJuJmJjeXcxEfc7xxKUydvxRKqvHg%2BaGaYuYZ6tQ3VkdpBo52f3ngzRxsK7WCeFDx%2BwYeWTq%2BW%2BpvRLN9zxi15Y9fPUUzVAvgb9uaIZK9efrVSDRlzGSoeESXdg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/wandb-metadata.json?Expires=1669202119&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vb0CRMCq988DTCyaZJIquQPI65NLK5RNT8aexZJrsg3rAYec7r31HrVzSIsmT5YF4Zv6DlaYIETAGXp4%2B1%2FtnLiwDoq9iYlK%2FOdMGcXJ%2BcLOEEWpsFvZSyaA%2FzVH9DBpB5urleq0oHiJ%2BsnNBZhuN0U9f2dlwrUJi4M7D7pNdMm2DOOFnTHayb2JWbDcfaiwTODwUwT4neM58ey7tue2toTNXuhtJuJmJjeXcxEfc7xxKUydvxRKqvHg%2BaGaYuYZ6tQ3VkdpBo52f3ngzRxsK7WCeFDx%2BwYeWTq%2BW%2BpvRLN9zxi15Y9fPUUzVAvgb9uaIZK9efrVSDRlzGSoeESXdg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c83cf100>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:15:53,786 ERROR   Thread-20 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2652'}
2022-11-22 19:15:53,786 ERROR   Thread-20 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:15:56,535 DEBUG   HandlerThread:37387 [handler.py:handle_request():139] handle_request: keepalive
2022-11-22 19:16:03,023 ERROR   Thread-25 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/conda-environment.yaml?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=OaUG6QXNz%2FTlE6iOzLGAD%2Bhg9CfkQtXLH5nTRLTw9guiGtxCtw%2FvHdjZ0TD%2BYiDgJD4a02dvFuxSt0%2B7AhXP%2Fei8a%2BAo%2B7aqstpjNlApPtnDFc9tfaRFfwm6m0fv%2BkLHsawUCnKv6%2Bkg6%2FjKaxNnkKlo5cIY22Q%2FUVtDtI6L3xaW1ILbxXp2L0Boa49cq5vH5XF2j266%2BMHwSwVeCRZo3f3lmTrRbWPeZVgsTm0hJgNAbjziNTFz3eSdIIvfA4C2tM8SkYsEjimECGaBOqU5TgOWWJlwTi2Jy6oO3jL9%2FcXpM8RLNcqAM2Cgzo2qFJytSyHMFoue3RBv6aY4s8Yj3w%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/conda-environment.yaml?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=OaUG6QXNz%2FTlE6iOzLGAD%2Bhg9CfkQtXLH5nTRLTw9guiGtxCtw%2FvHdjZ0TD%2BYiDgJD4a02dvFuxSt0%2B7AhXP%2Fei8a%2BAo%2B7aqstpjNlApPtnDFc9tfaRFfwm6m0fv%2BkLHsawUCnKv6%2Bkg6%2FjKaxNnkKlo5cIY22Q%2FUVtDtI6L3xaW1ILbxXp2L0Boa49cq5vH5XF2j266%2BMHwSwVeCRZo3f3lmTrRbWPeZVgsTm0hJgNAbjziNTFz3eSdIIvfA4C2tM8SkYsEjimECGaBOqU5TgOWWJlwTi2Jy6oO3jL9%2FcXpM8RLNcqAM2Cgzo2qFJytSyHMFoue3RBv6aY4s8Yj3w%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c82e9a30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:16:03,024 ERROR   Thread-25 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6342'}
2022-11-22 19:16:03,024 ERROR   Thread-25 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:16:03,060 ERROR   Thread-22 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/config.yaml?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=QuoiPlWEUg%2FwmuqrLgbKBgCQhd2Tt1lNE1O1%2BwuI1mjVEKmzltZ57Z%2BmesWBfz4HWYCuqlG0cWPVStkQl8H9cpY3J1NZPYiIlTo3Wd7ZEwECQTTQDYe9SgFXfvSoZPvX%2FJ8zz0G7GXDtqGEgznk8gP8GvzKTllg34E0zdRwgVC5OZeG73edS2%2F7%2FxmtUK9osx6ydbwo8X1%2FfqA%2F1i0Thv9MobwhvUCE3hJCQgK00Hbj4pyAhvYmgfhr2oayEZ9eBK20vNMHpMNXPbKOTKCd07L%2BL7upteHiArR65W753ZXw8YJOr%2BhQdLpt7vYIX9kcNF7dfS%2Bma7cAdATKSgrcVGw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/config.yaml?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=QuoiPlWEUg%2FwmuqrLgbKBgCQhd2Tt1lNE1O1%2BwuI1mjVEKmzltZ57Z%2BmesWBfz4HWYCuqlG0cWPVStkQl8H9cpY3J1NZPYiIlTo3Wd7ZEwECQTTQDYe9SgFXfvSoZPvX%2FJ8zz0G7GXDtqGEgznk8gP8GvzKTllg34E0zdRwgVC5OZeG73edS2%2F7%2FxmtUK9osx6ydbwo8X1%2FfqA%2F1i0Thv9MobwhvUCE3hJCQgK00Hbj4pyAhvYmgfhr2oayEZ9eBK20vNMHpMNXPbKOTKCd07L%2BL7upteHiArR65W753ZXw8YJOr%2BhQdLpt7vYIX9kcNF7dfS%2Bma7cAdATKSgrcVGw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c85e9eb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:16:03,061 ERROR   Thread-22 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5112'}
2022-11-22 19:16:03,062 ERROR   Thread-22 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:16:03,063 ERROR   Thread-23 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/output.log?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Da9t7UJRzL8KOppQ0LGm8uCvE56atWOTDjF9NjCEr5d4jhQMjkK2S4wUeV2rjileH%2BEJFdjMpn3PYcIPoMNP0XtIoTFnzYlC%2F908fGpc3Lt0IAtYvV4Ol5s5SI7DA7OBpP3GDQ4z%2BQRhGkIkiu6Ku%2F5mWejTG0p3vPSMny2rq%2F0gjdmKCQYHJ%2FApGpxJbjTeuKaFpXsVPKym9%2Ftd4gTXA%2BZKmvHC%2FCLsxwt32aOfjGxRdsr%2FpB6OIJ3IdPnS31an6hgsPy5JKVcVHnug24EG09EXVd8WrgHv6OLn8Ng%2BZzr480%2Bb5IaS2RytC%2BYTDn3XWBw2qmig7IxK6u3rnu6YoQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/output.log?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Da9t7UJRzL8KOppQ0LGm8uCvE56atWOTDjF9NjCEr5d4jhQMjkK2S4wUeV2rjileH%2BEJFdjMpn3PYcIPoMNP0XtIoTFnzYlC%2F908fGpc3Lt0IAtYvV4Ol5s5SI7DA7OBpP3GDQ4z%2BQRhGkIkiu6Ku%2F5mWejTG0p3vPSMny2rq%2F0gjdmKCQYHJ%2FApGpxJbjTeuKaFpXsVPKym9%2Ftd4gTXA%2BZKmvHC%2FCLsxwt32aOfjGxRdsr%2FpB6OIJ3IdPnS31an6hgsPy5JKVcVHnug24EG09EXVd8WrgHv6OLn8Ng%2BZzr480%2Bb5IaS2RytC%2BYTDn3XWBw2qmig7IxK6u3rnu6YoQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c82f18e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:16:03,064 ERROR   Thread-23 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '11198'}
2022-11-22 19:16:03,065 ERROR   Thread-23 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:16:03,190 ERROR   Thread-24 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/requirements.txt?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=AO6%2F5byvkZpfRQDchG8Vy6O2iAyDFFiWnDanTGNvzZx%2FWbVNe4jj80rn16hAvXVV%2FMUbpeYAzDB6Cx5CDMr5Z3vTgINGb9UzDJnD5NZnF8AkOFtd%2BjONVaXIeV94%2BUToJYLJa2sJ8%2FOAW2sF3Ccbj5rybvUh95RiOEMxpKmomjblsr6B7AoFDPtRUeyKdrg%2F3h5dRIws4kOuJ7Xx6GWN51n1zxQipxuX%2FFFf%2BXHyyllX7wqpCLmLRXwp3KTe8J%2F1Y8ttMoyZ8034WaYA9bC%2B0eRHdrgQsRJNdKRA38g86mzYo1fV0AZvdWpGxpVCm96S6KsOZ2yaP88XkEXo6uwWLg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/requirements.txt?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=AO6%2F5byvkZpfRQDchG8Vy6O2iAyDFFiWnDanTGNvzZx%2FWbVNe4jj80rn16hAvXVV%2FMUbpeYAzDB6Cx5CDMr5Z3vTgINGb9UzDJnD5NZnF8AkOFtd%2BjONVaXIeV94%2BUToJYLJa2sJ8%2FOAW2sF3Ccbj5rybvUh95RiOEMxpKmomjblsr6B7AoFDPtRUeyKdrg%2F3h5dRIws4kOuJ7Xx6GWN51n1zxQipxuX%2FFFf%2BXHyyllX7wqpCLmLRXwp3KTe8J%2F1Y8ttMoyZ8034WaYA9bC%2B0eRHdrgQsRJNdKRA38g86mzYo1fV0AZvdWpGxpVCm96S6KsOZ2yaP88XkEXo6uwWLg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c850e490>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:16:03,191 ERROR   Thread-24 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2140'}
2022-11-22 19:16:03,192 ERROR   Thread-24 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:16:03,458 ERROR   Thread-21 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/wandb-summary.json?Expires=1669202142&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=SuTOwp%2FBVfFV%2B5mYZ4Ve%2BxcIJJylnXDIdS8cixsfr0QT1cSU34JJwmGTRrqy5v33IlutI40GAsDt46iaOiTxU78EmAIe%2F5LQtiP7%2BMFigx%2FITG3f9y5rn1sXvzKI9u5aHcJSYYLaUP8gPg2ddeknWfqVjC0nMdkEDd2p%2B0HP7eNvYybf7oxKe%2FH15tehfeFyPdtPlEqqug4gRESBPg2uCbLZwYUZeejJCBgT%2BNpdO4z8fUjvkW%2B%2B04tWOS0Kjp4M4X%2BGRTWB4krKr%2F2z5ckVKbUQXGMXeRg2s1tJ%2BZTclptKIYmFYFveOI3VSlbgB0o11s6YEc5anf7MpjjJB4xcKw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/wandb-summary.json?Expires=1669202142&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=SuTOwp%2FBVfFV%2B5mYZ4Ve%2BxcIJJylnXDIdS8cixsfr0QT1cSU34JJwmGTRrqy5v33IlutI40GAsDt46iaOiTxU78EmAIe%2F5LQtiP7%2BMFigx%2FITG3f9y5rn1sXvzKI9u5aHcJSYYLaUP8gPg2ddeknWfqVjC0nMdkEDd2p%2B0HP7eNvYybf7oxKe%2FH15tehfeFyPdtPlEqqug4gRESBPg2uCbLZwYUZeejJCBgT%2BNpdO4z8fUjvkW%2B%2B04tWOS0Kjp4M4X%2BGRTWB4krKr%2F2z5ckVKbUQXGMXeRg2s1tJ%2BZTclptKIYmFYFveOI3VSlbgB0o11s6YEc5anf7MpjjJB4xcKw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c847ffa0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:16:03,458 ERROR   Thread-21 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2022-11-22 19:16:03,458 ERROR   Thread-21 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:16:03,682 WARNING StreamThr :37387 [internal.py:is_dead():385] Internal process exiting, parent pid 37357 disappeared
2022-11-22 19:16:03,682 ERROR   StreamThr :37387 [internal.py:wandb_internal():147] Internal process shutdown.
2022-11-22 19:16:04,146 INFO    WriterThread:37387 [datastore.py:close():279] close: /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191458-2vt5gtb1/run-2vt5gtb1.wandb
2022-11-22 19:16:04,381 INFO    SenderThread:37387 [sender.py:finish():1331] shutting down sender
2022-11-22 19:16:04,381 INFO    SenderThread:37387 [file_pusher.py:finish():168] shutting down file pusher
2022-11-22 19:16:04,382 INFO    SenderThread:37387 [file_pusher.py:join():173] waiting for file pusher
2022-11-22 19:16:04,545 INFO    HandlerThread:37387 [handler.py:finish():814] shutting down handler
2022-11-22 19:16:08,542 ERROR   Thread-20 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/wandb-metadata.json?Expires=1669202119&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vb0CRMCq988DTCyaZJIquQPI65NLK5RNT8aexZJrsg3rAYec7r31HrVzSIsmT5YF4Zv6DlaYIETAGXp4%2B1%2FtnLiwDoq9iYlK%2FOdMGcXJ%2BcLOEEWpsFvZSyaA%2FzVH9DBpB5urleq0oHiJ%2BsnNBZhuN0U9f2dlwrUJi4M7D7pNdMm2DOOFnTHayb2JWbDcfaiwTODwUwT4neM58ey7tue2toTNXuhtJuJmJjeXcxEfc7xxKUydvxRKqvHg%2BaGaYuYZ6tQ3VkdpBo52f3ngzRxsK7WCeFDx%2BwYeWTq%2BW%2BpvRLN9zxi15Y9fPUUzVAvgb9uaIZK9efrVSDRlzGSoeESXdg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/wandb-metadata.json?Expires=1669202119&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vb0CRMCq988DTCyaZJIquQPI65NLK5RNT8aexZJrsg3rAYec7r31HrVzSIsmT5YF4Zv6DlaYIETAGXp4%2B1%2FtnLiwDoq9iYlK%2FOdMGcXJ%2BcLOEEWpsFvZSyaA%2FzVH9DBpB5urleq0oHiJ%2BsnNBZhuN0U9f2dlwrUJi4M7D7pNdMm2DOOFnTHayb2JWbDcfaiwTODwUwT4neM58ey7tue2toTNXuhtJuJmJjeXcxEfc7xxKUydvxRKqvHg%2BaGaYuYZ6tQ3VkdpBo52f3ngzRxsK7WCeFDx%2BwYeWTq%2BW%2BpvRLN9zxi15Y9fPUUzVAvgb9uaIZK9efrVSDRlzGSoeESXdg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c847f6d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:16:08,542 ERROR   Thread-20 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2652'}
2022-11-22 19:16:08,542 ERROR   Thread-20 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:16:15,252 ERROR   Thread-23 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/output.log?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Da9t7UJRzL8KOppQ0LGm8uCvE56atWOTDjF9NjCEr5d4jhQMjkK2S4wUeV2rjileH%2BEJFdjMpn3PYcIPoMNP0XtIoTFnzYlC%2F908fGpc3Lt0IAtYvV4Ol5s5SI7DA7OBpP3GDQ4z%2BQRhGkIkiu6Ku%2F5mWejTG0p3vPSMny2rq%2F0gjdmKCQYHJ%2FApGpxJbjTeuKaFpXsVPKym9%2Ftd4gTXA%2BZKmvHC%2FCLsxwt32aOfjGxRdsr%2FpB6OIJ3IdPnS31an6hgsPy5JKVcVHnug24EG09EXVd8WrgHv6OLn8Ng%2BZzr480%2Bb5IaS2RytC%2BYTDn3XWBw2qmig7IxK6u3rnu6YoQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/output.log?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Da9t7UJRzL8KOppQ0LGm8uCvE56atWOTDjF9NjCEr5d4jhQMjkK2S4wUeV2rjileH%2BEJFdjMpn3PYcIPoMNP0XtIoTFnzYlC%2F908fGpc3Lt0IAtYvV4Ol5s5SI7DA7OBpP3GDQ4z%2BQRhGkIkiu6Ku%2F5mWejTG0p3vPSMny2rq%2F0gjdmKCQYHJ%2FApGpxJbjTeuKaFpXsVPKym9%2Ftd4gTXA%2BZKmvHC%2FCLsxwt32aOfjGxRdsr%2FpB6OIJ3IdPnS31an6hgsPy5JKVcVHnug24EG09EXVd8WrgHv6OLn8Ng%2BZzr480%2Bb5IaS2RytC%2BYTDn3XWBw2qmig7IxK6u3rnu6YoQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c85d3340>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:16:15,253 ERROR   Thread-23 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '11198'}
2022-11-22 19:16:15,253 ERROR   Thread-23 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:16:15,364 ERROR   Thread-22 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/config.yaml?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=QuoiPlWEUg%2FwmuqrLgbKBgCQhd2Tt1lNE1O1%2BwuI1mjVEKmzltZ57Z%2BmesWBfz4HWYCuqlG0cWPVStkQl8H9cpY3J1NZPYiIlTo3Wd7ZEwECQTTQDYe9SgFXfvSoZPvX%2FJ8zz0G7GXDtqGEgznk8gP8GvzKTllg34E0zdRwgVC5OZeG73edS2%2F7%2FxmtUK9osx6ydbwo8X1%2FfqA%2F1i0Thv9MobwhvUCE3hJCQgK00Hbj4pyAhvYmgfhr2oayEZ9eBK20vNMHpMNXPbKOTKCd07L%2BL7upteHiArR65W753ZXw8YJOr%2BhQdLpt7vYIX9kcNF7dfS%2Bma7cAdATKSgrcVGw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/config.yaml?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=QuoiPlWEUg%2FwmuqrLgbKBgCQhd2Tt1lNE1O1%2BwuI1mjVEKmzltZ57Z%2BmesWBfz4HWYCuqlG0cWPVStkQl8H9cpY3J1NZPYiIlTo3Wd7ZEwECQTTQDYe9SgFXfvSoZPvX%2FJ8zz0G7GXDtqGEgznk8gP8GvzKTllg34E0zdRwgVC5OZeG73edS2%2F7%2FxmtUK9osx6ydbwo8X1%2FfqA%2F1i0Thv9MobwhvUCE3hJCQgK00Hbj4pyAhvYmgfhr2oayEZ9eBK20vNMHpMNXPbKOTKCd07L%2BL7upteHiArR65W753ZXw8YJOr%2BhQdLpt7vYIX9kcNF7dfS%2Bma7cAdATKSgrcVGw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c847f460>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:16:15,365 ERROR   Thread-22 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5112'}
2022-11-22 19:16:15,365 ERROR   Thread-22 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:16:15,433 ERROR   Thread-24 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/requirements.txt?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=AO6%2F5byvkZpfRQDchG8Vy6O2iAyDFFiWnDanTGNvzZx%2FWbVNe4jj80rn16hAvXVV%2FMUbpeYAzDB6Cx5CDMr5Z3vTgINGb9UzDJnD5NZnF8AkOFtd%2BjONVaXIeV94%2BUToJYLJa2sJ8%2FOAW2sF3Ccbj5rybvUh95RiOEMxpKmomjblsr6B7AoFDPtRUeyKdrg%2F3h5dRIws4kOuJ7Xx6GWN51n1zxQipxuX%2FFFf%2BXHyyllX7wqpCLmLRXwp3KTe8J%2F1Y8ttMoyZ8034WaYA9bC%2B0eRHdrgQsRJNdKRA38g86mzYo1fV0AZvdWpGxpVCm96S6KsOZ2yaP88XkEXo6uwWLg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/requirements.txt?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=AO6%2F5byvkZpfRQDchG8Vy6O2iAyDFFiWnDanTGNvzZx%2FWbVNe4jj80rn16hAvXVV%2FMUbpeYAzDB6Cx5CDMr5Z3vTgINGb9UzDJnD5NZnF8AkOFtd%2BjONVaXIeV94%2BUToJYLJa2sJ8%2FOAW2sF3Ccbj5rybvUh95RiOEMxpKmomjblsr6B7AoFDPtRUeyKdrg%2F3h5dRIws4kOuJ7Xx6GWN51n1zxQipxuX%2FFFf%2BXHyyllX7wqpCLmLRXwp3KTe8J%2F1Y8ttMoyZ8034WaYA9bC%2B0eRHdrgQsRJNdKRA38g86mzYo1fV0AZvdWpGxpVCm96S6KsOZ2yaP88XkEXo6uwWLg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c865daf0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:16:15,434 ERROR   Thread-24 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2140'}
2022-11-22 19:16:15,435 ERROR   Thread-24 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:16:15,476 ERROR   Thread-25 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/conda-environment.yaml?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=OaUG6QXNz%2FTlE6iOzLGAD%2Bhg9CfkQtXLH5nTRLTw9guiGtxCtw%2FvHdjZ0TD%2BYiDgJD4a02dvFuxSt0%2B7AhXP%2Fei8a%2BAo%2B7aqstpjNlApPtnDFc9tfaRFfwm6m0fv%2BkLHsawUCnKv6%2Bkg6%2FjKaxNnkKlo5cIY22Q%2FUVtDtI6L3xaW1ILbxXp2L0Boa49cq5vH5XF2j266%2BMHwSwVeCRZo3f3lmTrRbWPeZVgsTm0hJgNAbjziNTFz3eSdIIvfA4C2tM8SkYsEjimECGaBOqU5TgOWWJlwTi2Jy6oO3jL9%2FcXpM8RLNcqAM2Cgzo2qFJytSyHMFoue3RBv6aY4s8Yj3w%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/conda-environment.yaml?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=OaUG6QXNz%2FTlE6iOzLGAD%2Bhg9CfkQtXLH5nTRLTw9guiGtxCtw%2FvHdjZ0TD%2BYiDgJD4a02dvFuxSt0%2B7AhXP%2Fei8a%2BAo%2B7aqstpjNlApPtnDFc9tfaRFfwm6m0fv%2BkLHsawUCnKv6%2Bkg6%2FjKaxNnkKlo5cIY22Q%2FUVtDtI6L3xaW1ILbxXp2L0Boa49cq5vH5XF2j266%2BMHwSwVeCRZo3f3lmTrRbWPeZVgsTm0hJgNAbjziNTFz3eSdIIvfA4C2tM8SkYsEjimECGaBOqU5TgOWWJlwTi2Jy6oO3jL9%2FcXpM8RLNcqAM2Cgzo2qFJytSyHMFoue3RBv6aY4s8Yj3w%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c83cfb50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:16:15,477 ERROR   Thread-25 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6342'}
2022-11-22 19:16:15,477 ERROR   Thread-25 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:16:15,903 ERROR   Thread-21 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/wandb-summary.json?Expires=1669202142&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=SuTOwp%2FBVfFV%2B5mYZ4Ve%2BxcIJJylnXDIdS8cixsfr0QT1cSU34JJwmGTRrqy5v33IlutI40GAsDt46iaOiTxU78EmAIe%2F5LQtiP7%2BMFigx%2FITG3f9y5rn1sXvzKI9u5aHcJSYYLaUP8gPg2ddeknWfqVjC0nMdkEDd2p%2B0HP7eNvYybf7oxKe%2FH15tehfeFyPdtPlEqqug4gRESBPg2uCbLZwYUZeejJCBgT%2BNpdO4z8fUjvkW%2B%2B04tWOS0Kjp4M4X%2BGRTWB4krKr%2F2z5ckVKbUQXGMXeRg2s1tJ%2BZTclptKIYmFYFveOI3VSlbgB0o11s6YEc5anf7MpjjJB4xcKw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/wandb-summary.json?Expires=1669202142&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=SuTOwp%2FBVfFV%2B5mYZ4Ve%2BxcIJJylnXDIdS8cixsfr0QT1cSU34JJwmGTRrqy5v33IlutI40GAsDt46iaOiTxU78EmAIe%2F5LQtiP7%2BMFigx%2FITG3f9y5rn1sXvzKI9u5aHcJSYYLaUP8gPg2ddeknWfqVjC0nMdkEDd2p%2B0HP7eNvYybf7oxKe%2FH15tehfeFyPdtPlEqqug4gRESBPg2uCbLZwYUZeejJCBgT%2BNpdO4z8fUjvkW%2B%2B04tWOS0Kjp4M4X%2BGRTWB4krKr%2F2z5ckVKbUQXGMXeRg2s1tJ%2BZTclptKIYmFYFveOI3VSlbgB0o11s6YEc5anf7MpjjJB4xcKw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c82e9cd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:16:15,904 ERROR   Thread-21 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2022-11-22 19:16:15,904 ERROR   Thread-21 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:16:26,791 ERROR   Thread-20 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/wandb-metadata.json?Expires=1669202119&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vb0CRMCq988DTCyaZJIquQPI65NLK5RNT8aexZJrsg3rAYec7r31HrVzSIsmT5YF4Zv6DlaYIETAGXp4%2B1%2FtnLiwDoq9iYlK%2FOdMGcXJ%2BcLOEEWpsFvZSyaA%2FzVH9DBpB5urleq0oHiJ%2BsnNBZhuN0U9f2dlwrUJi4M7D7pNdMm2DOOFnTHayb2JWbDcfaiwTODwUwT4neM58ey7tue2toTNXuhtJuJmJjeXcxEfc7xxKUydvxRKqvHg%2BaGaYuYZ6tQ3VkdpBo52f3ngzRxsK7WCeFDx%2BwYeWTq%2BW%2BpvRLN9zxi15Y9fPUUzVAvgb9uaIZK9efrVSDRlzGSoeESXdg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/wandb-metadata.json?Expires=1669202119&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vb0CRMCq988DTCyaZJIquQPI65NLK5RNT8aexZJrsg3rAYec7r31HrVzSIsmT5YF4Zv6DlaYIETAGXp4%2B1%2FtnLiwDoq9iYlK%2FOdMGcXJ%2BcLOEEWpsFvZSyaA%2FzVH9DBpB5urleq0oHiJ%2BsnNBZhuN0U9f2dlwrUJi4M7D7pNdMm2DOOFnTHayb2JWbDcfaiwTODwUwT4neM58ey7tue2toTNXuhtJuJmJjeXcxEfc7xxKUydvxRKqvHg%2BaGaYuYZ6tQ3VkdpBo52f3ngzRxsK7WCeFDx%2BwYeWTq%2BW%2BpvRLN9zxi15Y9fPUUzVAvgb9uaIZK9efrVSDRlzGSoeESXdg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48e695ff10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:16:26,791 ERROR   Thread-20 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2652'}
2022-11-22 19:16:26,791 ERROR   Thread-20 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:16:29,691 ERROR   Thread-23 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/output.log?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Da9t7UJRzL8KOppQ0LGm8uCvE56atWOTDjF9NjCEr5d4jhQMjkK2S4wUeV2rjileH%2BEJFdjMpn3PYcIPoMNP0XtIoTFnzYlC%2F908fGpc3Lt0IAtYvV4Ol5s5SI7DA7OBpP3GDQ4z%2BQRhGkIkiu6Ku%2F5mWejTG0p3vPSMny2rq%2F0gjdmKCQYHJ%2FApGpxJbjTeuKaFpXsVPKym9%2Ftd4gTXA%2BZKmvHC%2FCLsxwt32aOfjGxRdsr%2FpB6OIJ3IdPnS31an6hgsPy5JKVcVHnug24EG09EXVd8WrgHv6OLn8Ng%2BZzr480%2Bb5IaS2RytC%2BYTDn3XWBw2qmig7IxK6u3rnu6YoQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/output.log?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Da9t7UJRzL8KOppQ0LGm8uCvE56atWOTDjF9NjCEr5d4jhQMjkK2S4wUeV2rjileH%2BEJFdjMpn3PYcIPoMNP0XtIoTFnzYlC%2F908fGpc3Lt0IAtYvV4Ol5s5SI7DA7OBpP3GDQ4z%2BQRhGkIkiu6Ku%2F5mWejTG0p3vPSMny2rq%2F0gjdmKCQYHJ%2FApGpxJbjTeuKaFpXsVPKym9%2Ftd4gTXA%2BZKmvHC%2FCLsxwt32aOfjGxRdsr%2FpB6OIJ3IdPnS31an6hgsPy5JKVcVHnug24EG09EXVd8WrgHv6OLn8Ng%2BZzr480%2Bb5IaS2RytC%2BYTDn3XWBw2qmig7IxK6u3rnu6YoQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c83cfa00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:16:29,691 ERROR   Thread-23 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '11198'}
2022-11-22 19:16:29,692 ERROR   Thread-23 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:16:30,056 ERROR   Thread-25 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/conda-environment.yaml?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=OaUG6QXNz%2FTlE6iOzLGAD%2Bhg9CfkQtXLH5nTRLTw9guiGtxCtw%2FvHdjZ0TD%2BYiDgJD4a02dvFuxSt0%2B7AhXP%2Fei8a%2BAo%2B7aqstpjNlApPtnDFc9tfaRFfwm6m0fv%2BkLHsawUCnKv6%2Bkg6%2FjKaxNnkKlo5cIY22Q%2FUVtDtI6L3xaW1ILbxXp2L0Boa49cq5vH5XF2j266%2BMHwSwVeCRZo3f3lmTrRbWPeZVgsTm0hJgNAbjziNTFz3eSdIIvfA4C2tM8SkYsEjimECGaBOqU5TgOWWJlwTi2Jy6oO3jL9%2FcXpM8RLNcqAM2Cgzo2qFJytSyHMFoue3RBv6aY4s8Yj3w%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/conda-environment.yaml?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=OaUG6QXNz%2FTlE6iOzLGAD%2Bhg9CfkQtXLH5nTRLTw9guiGtxCtw%2FvHdjZ0TD%2BYiDgJD4a02dvFuxSt0%2B7AhXP%2Fei8a%2BAo%2B7aqstpjNlApPtnDFc9tfaRFfwm6m0fv%2BkLHsawUCnKv6%2Bkg6%2FjKaxNnkKlo5cIY22Q%2FUVtDtI6L3xaW1ILbxXp2L0Boa49cq5vH5XF2j266%2BMHwSwVeCRZo3f3lmTrRbWPeZVgsTm0hJgNAbjziNTFz3eSdIIvfA4C2tM8SkYsEjimECGaBOqU5TgOWWJlwTi2Jy6oO3jL9%2FcXpM8RLNcqAM2Cgzo2qFJytSyHMFoue3RBv6aY4s8Yj3w%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c84c2610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:16:30,056 ERROR   Thread-25 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6342'}
2022-11-22 19:16:30,057 ERROR   Thread-25 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:16:30,224 ERROR   Thread-24 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/requirements.txt?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=AO6%2F5byvkZpfRQDchG8Vy6O2iAyDFFiWnDanTGNvzZx%2FWbVNe4jj80rn16hAvXVV%2FMUbpeYAzDB6Cx5CDMr5Z3vTgINGb9UzDJnD5NZnF8AkOFtd%2BjONVaXIeV94%2BUToJYLJa2sJ8%2FOAW2sF3Ccbj5rybvUh95RiOEMxpKmomjblsr6B7AoFDPtRUeyKdrg%2F3h5dRIws4kOuJ7Xx6GWN51n1zxQipxuX%2FFFf%2BXHyyllX7wqpCLmLRXwp3KTe8J%2F1Y8ttMoyZ8034WaYA9bC%2B0eRHdrgQsRJNdKRA38g86mzYo1fV0AZvdWpGxpVCm96S6KsOZ2yaP88XkEXo6uwWLg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/requirements.txt?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=AO6%2F5byvkZpfRQDchG8Vy6O2iAyDFFiWnDanTGNvzZx%2FWbVNe4jj80rn16hAvXVV%2FMUbpeYAzDB6Cx5CDMr5Z3vTgINGb9UzDJnD5NZnF8AkOFtd%2BjONVaXIeV94%2BUToJYLJa2sJ8%2FOAW2sF3Ccbj5rybvUh95RiOEMxpKmomjblsr6B7AoFDPtRUeyKdrg%2F3h5dRIws4kOuJ7Xx6GWN51n1zxQipxuX%2FFFf%2BXHyyllX7wqpCLmLRXwp3KTe8J%2F1Y8ttMoyZ8034WaYA9bC%2B0eRHdrgQsRJNdKRA38g86mzYo1fV0AZvdWpGxpVCm96S6KsOZ2yaP88XkEXo6uwWLg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c8505ee0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:16:30,225 ERROR   Thread-24 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2140'}
2022-11-22 19:16:30,225 ERROR   Thread-24 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:16:30,342 ERROR   Thread-22 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/config.yaml?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=QuoiPlWEUg%2FwmuqrLgbKBgCQhd2Tt1lNE1O1%2BwuI1mjVEKmzltZ57Z%2BmesWBfz4HWYCuqlG0cWPVStkQl8H9cpY3J1NZPYiIlTo3Wd7ZEwECQTTQDYe9SgFXfvSoZPvX%2FJ8zz0G7GXDtqGEgznk8gP8GvzKTllg34E0zdRwgVC5OZeG73edS2%2F7%2FxmtUK9osx6ydbwo8X1%2FfqA%2F1i0Thv9MobwhvUCE3hJCQgK00Hbj4pyAhvYmgfhr2oayEZ9eBK20vNMHpMNXPbKOTKCd07L%2BL7upteHiArR65W753ZXw8YJOr%2BhQdLpt7vYIX9kcNF7dfS%2Bma7cAdATKSgrcVGw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/config.yaml?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=QuoiPlWEUg%2FwmuqrLgbKBgCQhd2Tt1lNE1O1%2BwuI1mjVEKmzltZ57Z%2BmesWBfz4HWYCuqlG0cWPVStkQl8H9cpY3J1NZPYiIlTo3Wd7ZEwECQTTQDYe9SgFXfvSoZPvX%2FJ8zz0G7GXDtqGEgznk8gP8GvzKTllg34E0zdRwgVC5OZeG73edS2%2F7%2FxmtUK9osx6ydbwo8X1%2FfqA%2F1i0Thv9MobwhvUCE3hJCQgK00Hbj4pyAhvYmgfhr2oayEZ9eBK20vNMHpMNXPbKOTKCd07L%2BL7upteHiArR65W753ZXw8YJOr%2BhQdLpt7vYIX9kcNF7dfS%2Bma7cAdATKSgrcVGw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c847f940>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:16:30,343 ERROR   Thread-22 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5112'}
2022-11-22 19:16:30,344 ERROR   Thread-22 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:16:30,452 ERROR   Thread-21 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/wandb-summary.json?Expires=1669202142&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=SuTOwp%2FBVfFV%2B5mYZ4Ve%2BxcIJJylnXDIdS8cixsfr0QT1cSU34JJwmGTRrqy5v33IlutI40GAsDt46iaOiTxU78EmAIe%2F5LQtiP7%2BMFigx%2FITG3f9y5rn1sXvzKI9u5aHcJSYYLaUP8gPg2ddeknWfqVjC0nMdkEDd2p%2B0HP7eNvYybf7oxKe%2FH15tehfeFyPdtPlEqqug4gRESBPg2uCbLZwYUZeejJCBgT%2BNpdO4z8fUjvkW%2B%2B04tWOS0Kjp4M4X%2BGRTWB4krKr%2F2z5ckVKbUQXGMXeRg2s1tJ%2BZTclptKIYmFYFveOI3VSlbgB0o11s6YEc5anf7MpjjJB4xcKw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/wandb-summary.json?Expires=1669202142&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=SuTOwp%2FBVfFV%2B5mYZ4Ve%2BxcIJJylnXDIdS8cixsfr0QT1cSU34JJwmGTRrqy5v33IlutI40GAsDt46iaOiTxU78EmAIe%2F5LQtiP7%2BMFigx%2FITG3f9y5rn1sXvzKI9u5aHcJSYYLaUP8gPg2ddeknWfqVjC0nMdkEDd2p%2B0HP7eNvYybf7oxKe%2FH15tehfeFyPdtPlEqqug4gRESBPg2uCbLZwYUZeejJCBgT%2BNpdO4z8fUjvkW%2B%2B04tWOS0Kjp4M4X%2BGRTWB4krKr%2F2z5ckVKbUQXGMXeRg2s1tJ%2BZTclptKIYmFYFveOI3VSlbgB0o11s6YEc5anf7MpjjJB4xcKw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c82e9310>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:16:30,453 ERROR   Thread-21 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2022-11-22 19:16:30,453 ERROR   Thread-21 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:16:48,838 ERROR   Thread-23 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/output.log?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Da9t7UJRzL8KOppQ0LGm8uCvE56atWOTDjF9NjCEr5d4jhQMjkK2S4wUeV2rjileH%2BEJFdjMpn3PYcIPoMNP0XtIoTFnzYlC%2F908fGpc3Lt0IAtYvV4Ol5s5SI7DA7OBpP3GDQ4z%2BQRhGkIkiu6Ku%2F5mWejTG0p3vPSMny2rq%2F0gjdmKCQYHJ%2FApGpxJbjTeuKaFpXsVPKym9%2Ftd4gTXA%2BZKmvHC%2FCLsxwt32aOfjGxRdsr%2FpB6OIJ3IdPnS31an6hgsPy5JKVcVHnug24EG09EXVd8WrgHv6OLn8Ng%2BZzr480%2Bb5IaS2RytC%2BYTDn3XWBw2qmig7IxK6u3rnu6YoQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/output.log?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Da9t7UJRzL8KOppQ0LGm8uCvE56atWOTDjF9NjCEr5d4jhQMjkK2S4wUeV2rjileH%2BEJFdjMpn3PYcIPoMNP0XtIoTFnzYlC%2F908fGpc3Lt0IAtYvV4Ol5s5SI7DA7OBpP3GDQ4z%2BQRhGkIkiu6Ku%2F5mWejTG0p3vPSMny2rq%2F0gjdmKCQYHJ%2FApGpxJbjTeuKaFpXsVPKym9%2Ftd4gTXA%2BZKmvHC%2FCLsxwt32aOfjGxRdsr%2FpB6OIJ3IdPnS31an6hgsPy5JKVcVHnug24EG09EXVd8WrgHv6OLn8Ng%2BZzr480%2Bb5IaS2RytC%2BYTDn3XWBw2qmig7IxK6u3rnu6YoQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c82f5b20>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:16:48,838 ERROR   Thread-23 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '11198'}
2022-11-22 19:16:48,838 ERROR   Thread-23 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:16:49,068 ERROR   Thread-21 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/wandb-summary.json?Expires=1669202142&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=SuTOwp%2FBVfFV%2B5mYZ4Ve%2BxcIJJylnXDIdS8cixsfr0QT1cSU34JJwmGTRrqy5v33IlutI40GAsDt46iaOiTxU78EmAIe%2F5LQtiP7%2BMFigx%2FITG3f9y5rn1sXvzKI9u5aHcJSYYLaUP8gPg2ddeknWfqVjC0nMdkEDd2p%2B0HP7eNvYybf7oxKe%2FH15tehfeFyPdtPlEqqug4gRESBPg2uCbLZwYUZeejJCBgT%2BNpdO4z8fUjvkW%2B%2B04tWOS0Kjp4M4X%2BGRTWB4krKr%2F2z5ckVKbUQXGMXeRg2s1tJ%2BZTclptKIYmFYFveOI3VSlbgB0o11s6YEc5anf7MpjjJB4xcKw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/wandb-summary.json?Expires=1669202142&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=SuTOwp%2FBVfFV%2B5mYZ4Ve%2BxcIJJylnXDIdS8cixsfr0QT1cSU34JJwmGTRrqy5v33IlutI40GAsDt46iaOiTxU78EmAIe%2F5LQtiP7%2BMFigx%2FITG3f9y5rn1sXvzKI9u5aHcJSYYLaUP8gPg2ddeknWfqVjC0nMdkEDd2p%2B0HP7eNvYybf7oxKe%2FH15tehfeFyPdtPlEqqug4gRESBPg2uCbLZwYUZeejJCBgT%2BNpdO4z8fUjvkW%2B%2B04tWOS0Kjp4M4X%2BGRTWB4krKr%2F2z5ckVKbUQXGMXeRg2s1tJ%2BZTclptKIYmFYFveOI3VSlbgB0o11s6YEc5anf7MpjjJB4xcKw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c82f5490>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:16:49,068 ERROR   Thread-21 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2022-11-22 19:16:49,068 ERROR   Thread-21 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:16:49,430 ERROR   Thread-25 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/conda-environment.yaml?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=OaUG6QXNz%2FTlE6iOzLGAD%2Bhg9CfkQtXLH5nTRLTw9guiGtxCtw%2FvHdjZ0TD%2BYiDgJD4a02dvFuxSt0%2B7AhXP%2Fei8a%2BAo%2B7aqstpjNlApPtnDFc9tfaRFfwm6m0fv%2BkLHsawUCnKv6%2Bkg6%2FjKaxNnkKlo5cIY22Q%2FUVtDtI6L3xaW1ILbxXp2L0Boa49cq5vH5XF2j266%2BMHwSwVeCRZo3f3lmTrRbWPeZVgsTm0hJgNAbjziNTFz3eSdIIvfA4C2tM8SkYsEjimECGaBOqU5TgOWWJlwTi2Jy6oO3jL9%2FcXpM8RLNcqAM2Cgzo2qFJytSyHMFoue3RBv6aY4s8Yj3w%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/conda-environment.yaml?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=OaUG6QXNz%2FTlE6iOzLGAD%2Bhg9CfkQtXLH5nTRLTw9guiGtxCtw%2FvHdjZ0TD%2BYiDgJD4a02dvFuxSt0%2B7AhXP%2Fei8a%2BAo%2B7aqstpjNlApPtnDFc9tfaRFfwm6m0fv%2BkLHsawUCnKv6%2Bkg6%2FjKaxNnkKlo5cIY22Q%2FUVtDtI6L3xaW1ILbxXp2L0Boa49cq5vH5XF2j266%2BMHwSwVeCRZo3f3lmTrRbWPeZVgsTm0hJgNAbjziNTFz3eSdIIvfA4C2tM8SkYsEjimECGaBOqU5TgOWWJlwTi2Jy6oO3jL9%2FcXpM8RLNcqAM2Cgzo2qFJytSyHMFoue3RBv6aY4s8Yj3w%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c82f1b80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:16:49,430 ERROR   Thread-25 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6342'}
2022-11-22 19:16:49,430 ERROR   Thread-25 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:16:49,490 ERROR   Thread-24 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/requirements.txt?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=AO6%2F5byvkZpfRQDchG8Vy6O2iAyDFFiWnDanTGNvzZx%2FWbVNe4jj80rn16hAvXVV%2FMUbpeYAzDB6Cx5CDMr5Z3vTgINGb9UzDJnD5NZnF8AkOFtd%2BjONVaXIeV94%2BUToJYLJa2sJ8%2FOAW2sF3Ccbj5rybvUh95RiOEMxpKmomjblsr6B7AoFDPtRUeyKdrg%2F3h5dRIws4kOuJ7Xx6GWN51n1zxQipxuX%2FFFf%2BXHyyllX7wqpCLmLRXwp3KTe8J%2F1Y8ttMoyZ8034WaYA9bC%2B0eRHdrgQsRJNdKRA38g86mzYo1fV0AZvdWpGxpVCm96S6KsOZ2yaP88XkEXo6uwWLg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/requirements.txt?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=AO6%2F5byvkZpfRQDchG8Vy6O2iAyDFFiWnDanTGNvzZx%2FWbVNe4jj80rn16hAvXVV%2FMUbpeYAzDB6Cx5CDMr5Z3vTgINGb9UzDJnD5NZnF8AkOFtd%2BjONVaXIeV94%2BUToJYLJa2sJ8%2FOAW2sF3Ccbj5rybvUh95RiOEMxpKmomjblsr6B7AoFDPtRUeyKdrg%2F3h5dRIws4kOuJ7Xx6GWN51n1zxQipxuX%2FFFf%2BXHyyllX7wqpCLmLRXwp3KTe8J%2F1Y8ttMoyZ8034WaYA9bC%2B0eRHdrgQsRJNdKRA38g86mzYo1fV0AZvdWpGxpVCm96S6KsOZ2yaP88XkEXo6uwWLg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c85d3310>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:16:49,490 ERROR   Thread-24 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2140'}
2022-11-22 19:16:49,490 ERROR   Thread-24 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:16:50,021 ERROR   Thread-22 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/config.yaml?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=QuoiPlWEUg%2FwmuqrLgbKBgCQhd2Tt1lNE1O1%2BwuI1mjVEKmzltZ57Z%2BmesWBfz4HWYCuqlG0cWPVStkQl8H9cpY3J1NZPYiIlTo3Wd7ZEwECQTTQDYe9SgFXfvSoZPvX%2FJ8zz0G7GXDtqGEgznk8gP8GvzKTllg34E0zdRwgVC5OZeG73edS2%2F7%2FxmtUK9osx6ydbwo8X1%2FfqA%2F1i0Thv9MobwhvUCE3hJCQgK00Hbj4pyAhvYmgfhr2oayEZ9eBK20vNMHpMNXPbKOTKCd07L%2BL7upteHiArR65W753ZXw8YJOr%2BhQdLpt7vYIX9kcNF7dfS%2Bma7cAdATKSgrcVGw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/config.yaml?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=QuoiPlWEUg%2FwmuqrLgbKBgCQhd2Tt1lNE1O1%2BwuI1mjVEKmzltZ57Z%2BmesWBfz4HWYCuqlG0cWPVStkQl8H9cpY3J1NZPYiIlTo3Wd7ZEwECQTTQDYe9SgFXfvSoZPvX%2FJ8zz0G7GXDtqGEgznk8gP8GvzKTllg34E0zdRwgVC5OZeG73edS2%2F7%2FxmtUK9osx6ydbwo8X1%2FfqA%2F1i0Thv9MobwhvUCE3hJCQgK00Hbj4pyAhvYmgfhr2oayEZ9eBK20vNMHpMNXPbKOTKCd07L%2BL7upteHiArR65W753ZXw8YJOr%2BhQdLpt7vYIX9kcNF7dfS%2Bma7cAdATKSgrcVGw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c847fd60>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:16:50,021 ERROR   Thread-22 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5112'}
2022-11-22 19:16:50,021 ERROR   Thread-22 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:16:53,626 ERROR   Thread-20 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/wandb-metadata.json?Expires=1669202119&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vb0CRMCq988DTCyaZJIquQPI65NLK5RNT8aexZJrsg3rAYec7r31HrVzSIsmT5YF4Zv6DlaYIETAGXp4%2B1%2FtnLiwDoq9iYlK%2FOdMGcXJ%2BcLOEEWpsFvZSyaA%2FzVH9DBpB5urleq0oHiJ%2BsnNBZhuN0U9f2dlwrUJi4M7D7pNdMm2DOOFnTHayb2JWbDcfaiwTODwUwT4neM58ey7tue2toTNXuhtJuJmJjeXcxEfc7xxKUydvxRKqvHg%2BaGaYuYZ6tQ3VkdpBo52f3ngzRxsK7WCeFDx%2BwYeWTq%2BW%2BpvRLN9zxi15Y9fPUUzVAvgb9uaIZK9efrVSDRlzGSoeESXdg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/wandb-metadata.json?Expires=1669202119&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vb0CRMCq988DTCyaZJIquQPI65NLK5RNT8aexZJrsg3rAYec7r31HrVzSIsmT5YF4Zv6DlaYIETAGXp4%2B1%2FtnLiwDoq9iYlK%2FOdMGcXJ%2BcLOEEWpsFvZSyaA%2FzVH9DBpB5urleq0oHiJ%2BsnNBZhuN0U9f2dlwrUJi4M7D7pNdMm2DOOFnTHayb2JWbDcfaiwTODwUwT4neM58ey7tue2toTNXuhtJuJmJjeXcxEfc7xxKUydvxRKqvHg%2BaGaYuYZ6tQ3VkdpBo52f3ngzRxsK7WCeFDx%2BwYeWTq%2BW%2BpvRLN9zxi15Y9fPUUzVAvgb9uaIZK9efrVSDRlzGSoeESXdg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c85058b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:16:53,626 ERROR   Thread-20 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2652'}
2022-11-22 19:16:53,626 ERROR   Thread-20 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:16,498 ERROR   Thread-25 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/conda-environment.yaml?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=OaUG6QXNz%2FTlE6iOzLGAD%2Bhg9CfkQtXLH5nTRLTw9guiGtxCtw%2FvHdjZ0TD%2BYiDgJD4a02dvFuxSt0%2B7AhXP%2Fei8a%2BAo%2B7aqstpjNlApPtnDFc9tfaRFfwm6m0fv%2BkLHsawUCnKv6%2Bkg6%2FjKaxNnkKlo5cIY22Q%2FUVtDtI6L3xaW1ILbxXp2L0Boa49cq5vH5XF2j266%2BMHwSwVeCRZo3f3lmTrRbWPeZVgsTm0hJgNAbjziNTFz3eSdIIvfA4C2tM8SkYsEjimECGaBOqU5TgOWWJlwTi2Jy6oO3jL9%2FcXpM8RLNcqAM2Cgzo2qFJytSyHMFoue3RBv6aY4s8Yj3w%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/conda-environment.yaml?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=OaUG6QXNz%2FTlE6iOzLGAD%2Bhg9CfkQtXLH5nTRLTw9guiGtxCtw%2FvHdjZ0TD%2BYiDgJD4a02dvFuxSt0%2B7AhXP%2Fei8a%2BAo%2B7aqstpjNlApPtnDFc9tfaRFfwm6m0fv%2BkLHsawUCnKv6%2Bkg6%2FjKaxNnkKlo5cIY22Q%2FUVtDtI6L3xaW1ILbxXp2L0Boa49cq5vH5XF2j266%2BMHwSwVeCRZo3f3lmTrRbWPeZVgsTm0hJgNAbjziNTFz3eSdIIvfA4C2tM8SkYsEjimECGaBOqU5TgOWWJlwTi2Jy6oO3jL9%2FcXpM8RLNcqAM2Cgzo2qFJytSyHMFoue3RBv6aY4s8Yj3w%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c84c2fa0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:16,499 ERROR   Thread-25 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '6342'}
2022-11-22 19:17:16,500 ERROR   Thread-25 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:17,288 ERROR   Thread-23 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/output.log?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Da9t7UJRzL8KOppQ0LGm8uCvE56atWOTDjF9NjCEr5d4jhQMjkK2S4wUeV2rjileH%2BEJFdjMpn3PYcIPoMNP0XtIoTFnzYlC%2F908fGpc3Lt0IAtYvV4Ol5s5SI7DA7OBpP3GDQ4z%2BQRhGkIkiu6Ku%2F5mWejTG0p3vPSMny2rq%2F0gjdmKCQYHJ%2FApGpxJbjTeuKaFpXsVPKym9%2Ftd4gTXA%2BZKmvHC%2FCLsxwt32aOfjGxRdsr%2FpB6OIJ3IdPnS31an6hgsPy5JKVcVHnug24EG09EXVd8WrgHv6OLn8Ng%2BZzr480%2Bb5IaS2RytC%2BYTDn3XWBw2qmig7IxK6u3rnu6YoQ%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/output.log?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Da9t7UJRzL8KOppQ0LGm8uCvE56atWOTDjF9NjCEr5d4jhQMjkK2S4wUeV2rjileH%2BEJFdjMpn3PYcIPoMNP0XtIoTFnzYlC%2F908fGpc3Lt0IAtYvV4Ol5s5SI7DA7OBpP3GDQ4z%2BQRhGkIkiu6Ku%2F5mWejTG0p3vPSMny2rq%2F0gjdmKCQYHJ%2FApGpxJbjTeuKaFpXsVPKym9%2Ftd4gTXA%2BZKmvHC%2FCLsxwt32aOfjGxRdsr%2FpB6OIJ3IdPnS31an6hgsPy5JKVcVHnug24EG09EXVd8WrgHv6OLn8Ng%2BZzr480%2Bb5IaS2RytC%2BYTDn3XWBw2qmig7IxK6u3rnu6YoQ%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c83cf490>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:17,289 ERROR   Thread-23 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '11198'}
2022-11-22 19:17:17,289 ERROR   Thread-23 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:18,327 ERROR   Thread-22 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/config.yaml?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=QuoiPlWEUg%2FwmuqrLgbKBgCQhd2Tt1lNE1O1%2BwuI1mjVEKmzltZ57Z%2BmesWBfz4HWYCuqlG0cWPVStkQl8H9cpY3J1NZPYiIlTo3Wd7ZEwECQTTQDYe9SgFXfvSoZPvX%2FJ8zz0G7GXDtqGEgznk8gP8GvzKTllg34E0zdRwgVC5OZeG73edS2%2F7%2FxmtUK9osx6ydbwo8X1%2FfqA%2F1i0Thv9MobwhvUCE3hJCQgK00Hbj4pyAhvYmgfhr2oayEZ9eBK20vNMHpMNXPbKOTKCd07L%2BL7upteHiArR65W753ZXw8YJOr%2BhQdLpt7vYIX9kcNF7dfS%2Bma7cAdATKSgrcVGw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/config.yaml?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=QuoiPlWEUg%2FwmuqrLgbKBgCQhd2Tt1lNE1O1%2BwuI1mjVEKmzltZ57Z%2BmesWBfz4HWYCuqlG0cWPVStkQl8H9cpY3J1NZPYiIlTo3Wd7ZEwECQTTQDYe9SgFXfvSoZPvX%2FJ8zz0G7GXDtqGEgznk8gP8GvzKTllg34E0zdRwgVC5OZeG73edS2%2F7%2FxmtUK9osx6ydbwo8X1%2FfqA%2F1i0Thv9MobwhvUCE3hJCQgK00Hbj4pyAhvYmgfhr2oayEZ9eBK20vNMHpMNXPbKOTKCd07L%2BL7upteHiArR65W753ZXw8YJOr%2BhQdLpt7vYIX9kcNF7dfS%2Bma7cAdATKSgrcVGw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c82f1cd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:18,329 ERROR   Thread-22 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '5112'}
2022-11-22 19:17:18,329 ERROR   Thread-22 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:18,666 ERROR   Thread-24 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/requirements.txt?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=AO6%2F5byvkZpfRQDchG8Vy6O2iAyDFFiWnDanTGNvzZx%2FWbVNe4jj80rn16hAvXVV%2FMUbpeYAzDB6Cx5CDMr5Z3vTgINGb9UzDJnD5NZnF8AkOFtd%2BjONVaXIeV94%2BUToJYLJa2sJ8%2FOAW2sF3Ccbj5rybvUh95RiOEMxpKmomjblsr6B7AoFDPtRUeyKdrg%2F3h5dRIws4kOuJ7Xx6GWN51n1zxQipxuX%2FFFf%2BXHyyllX7wqpCLmLRXwp3KTe8J%2F1Y8ttMoyZ8034WaYA9bC%2B0eRHdrgQsRJNdKRA38g86mzYo1fV0AZvdWpGxpVCm96S6KsOZ2yaP88XkEXo6uwWLg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/requirements.txt?Expires=1669202141&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=AO6%2F5byvkZpfRQDchG8Vy6O2iAyDFFiWnDanTGNvzZx%2FWbVNe4jj80rn16hAvXVV%2FMUbpeYAzDB6Cx5CDMr5Z3vTgINGb9UzDJnD5NZnF8AkOFtd%2BjONVaXIeV94%2BUToJYLJa2sJ8%2FOAW2sF3Ccbj5rybvUh95RiOEMxpKmomjblsr6B7AoFDPtRUeyKdrg%2F3h5dRIws4kOuJ7Xx6GWN51n1zxQipxuX%2FFFf%2BXHyyllX7wqpCLmLRXwp3KTe8J%2F1Y8ttMoyZ8034WaYA9bC%2B0eRHdrgQsRJNdKRA38g86mzYo1fV0AZvdWpGxpVCm96S6KsOZ2yaP88XkEXo6uwWLg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c82f1220>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:18,666 ERROR   Thread-24 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2140'}
2022-11-22 19:17:18,666 ERROR   Thread-24 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:18,880 ERROR   Thread-21 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/wandb-summary.json?Expires=1669202142&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=SuTOwp%2FBVfFV%2B5mYZ4Ve%2BxcIJJylnXDIdS8cixsfr0QT1cSU34JJwmGTRrqy5v33IlutI40GAsDt46iaOiTxU78EmAIe%2F5LQtiP7%2BMFigx%2FITG3f9y5rn1sXvzKI9u5aHcJSYYLaUP8gPg2ddeknWfqVjC0nMdkEDd2p%2B0HP7eNvYybf7oxKe%2FH15tehfeFyPdtPlEqqug4gRESBPg2uCbLZwYUZeejJCBgT%2BNpdO4z8fUjvkW%2B%2B04tWOS0Kjp4M4X%2BGRTWB4krKr%2F2z5ckVKbUQXGMXeRg2s1tJ%2BZTclptKIYmFYFveOI3VSlbgB0o11s6YEc5anf7MpjjJB4xcKw%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/wandb-summary.json?Expires=1669202142&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=SuTOwp%2FBVfFV%2B5mYZ4Ve%2BxcIJJylnXDIdS8cixsfr0QT1cSU34JJwmGTRrqy5v33IlutI40GAsDt46iaOiTxU78EmAIe%2F5LQtiP7%2BMFigx%2FITG3f9y5rn1sXvzKI9u5aHcJSYYLaUP8gPg2ddeknWfqVjC0nMdkEDd2p%2B0HP7eNvYybf7oxKe%2FH15tehfeFyPdtPlEqqug4gRESBPg2uCbLZwYUZeejJCBgT%2BNpdO4z8fUjvkW%2B%2B04tWOS0Kjp4M4X%2BGRTWB4krKr%2F2z5ckVKbUQXGMXeRg2s1tJ%2BZTclptKIYmFYFveOI3VSlbgB0o11s6YEc5anf7MpjjJB4xcKw%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c82f5970>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:18,881 ERROR   Thread-21 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '26'}
2022-11-22 19:17:18,881 ERROR   Thread-21 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:43,160 ERROR   Thread-20 :37387 [internal_api.py:upload_file():1926] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/wandb-metadata.json?Expires=1669202119&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vb0CRMCq988DTCyaZJIquQPI65NLK5RNT8aexZJrsg3rAYec7r31HrVzSIsmT5YF4Zv6DlaYIETAGXp4%2B1%2FtnLiwDoq9iYlK%2FOdMGcXJ%2BcLOEEWpsFvZSyaA%2FzVH9DBpB5urleq0oHiJ%2BsnNBZhuN0U9f2dlwrUJi4M7D7pNdMm2DOOFnTHayb2JWbDcfaiwTODwUwT4neM58ey7tue2toTNXuhtJuJmJjeXcxEfc7xxKUydvxRKqvHg%2BaGaYuYZ6tQ3VkdpBo52f3ngzRxsK7WCeFDx%2BwYeWTq%2BW%2BpvRLN9zxi15Y9fPUUzVAvgb9uaIZK9efrVSDRlzGSoeESXdg%3D%3D: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /wandb-production.appspot.com/broalantaps/YOLOR/2vt5gtb1/wandb-metadata.json?Expires=1669202119&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=Vb0CRMCq988DTCyaZJIquQPI65NLK5RNT8aexZJrsg3rAYec7r31HrVzSIsmT5YF4Zv6DlaYIETAGXp4%2B1%2FtnLiwDoq9iYlK%2FOdMGcXJ%2BcLOEEWpsFvZSyaA%2FzVH9DBpB5urleq0oHiJ%2BsnNBZhuN0U9f2dlwrUJi4M7D7pNdMm2DOOFnTHayb2JWbDcfaiwTODwUwT4neM58ey7tue2toTNXuhtJuJmJjeXcxEfc7xxKUydvxRKqvHg%2BaGaYuYZ6tQ3VkdpBo52f3ngzRxsK7WCeFDx%2BwYeWTq%2BW%2BpvRLN9zxi15Y9fPUUzVAvgb9uaIZK9efrVSDRlzGSoeESXdg%3D%3D (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f48c85dd160>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
2022-11-22 19:17:43,160 ERROR   Thread-20 :37387 [internal_api.py:upload_file():1928] upload_file request headers: {'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '2652'}
2022-11-22 19:17:43,160 ERROR   Thread-20 :37387 [internal_api.py:upload_file():1930] upload_file response body: 
2022-11-22 19:17:59,332 INFO    Thread-22 :37387 [upload_job.py:push():143] Uploaded file /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191458-2vt5gtb1/files/config.yaml
2022-11-22 19:17:59,418 INFO    Thread-23 :37387 [upload_job.py:push():143] Uploaded file /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191458-2vt5gtb1/files/output.log
2022-11-22 19:17:59,972 INFO    Thread-24 :37387 [upload_job.py:push():143] Uploaded file /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191458-2vt5gtb1/files/requirements.txt
2022-11-22 19:18:00,063 INFO    Thread-21 :37387 [upload_job.py:push():143] Uploaded file /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191458-2vt5gtb1/files/wandb-summary.json
2022-11-22 19:18:00,106 INFO    Thread-25 :37387 [upload_job.py:push():143] Uploaded file /home/rp/DeepLearning/yolov7-main/wandb/run-20221122_191458-2vt5gtb1/files/conda-environment.yaml
2022-11-22 19:18:54,087 INFO    Thread-20 :37387 [upload_job.py:push():143] Uploaded file /tmp/tmpzu2nvfytwandb/1sdxd9py-wandb-metadata.json
2022-11-22 19:18:54,289 INFO    Thread-16 :37387 [sender.py:transition_state():463] send defer: 9
